<a href="https://colab.research.google.com/github/Chandu106/pda/blob/main/expt5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.Create a two numpy 2D array of size 3x3 and compute the element-wise sum of the array and print the result.**


In [3]:
import numpy as np
array_1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

array_2 = np.array([[7,8,9],
                    [1,2,3],
                    [4,5,6]])

summation_result = array_1 + array_2
print(summation_result)

[[ 8 10 12]
 [ 5  7  9]
 [11 13 15]]


# **2.Create a numpy 2d array of 2X3 with random numbers and create large array by repeating the smaller array by 10 times**

In [9]:
smaller_array = np.random.rand(2,3)
larger_array = np.repeat(smaller_array, 10, axis = 0)
print("Smaller Array: ", smaller_array)
print("Larger Array: ", larger_array)

Smaller Array:  [[0.64674769 0.29076195 0.0219575 ]
 [0.52352267 0.66365415 0.51874747]]
Larger Array:  [[0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.64674769 0.29076195 0.0219575 ]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]
 [0.52352267 0.66365415 0.51874747]]


# **3.Create two 1D array on 5 elements with random numbers and print the position of elements where the 2 arrays match**

In [37]:
array_1 = np.random.randint(low=0, high=10, size=(1,5), dtype=int)
array_2 = np.random.randint(low=0, high=10, size=(1,5), dtype=int)
positions = np.where(array_1 == array_2)
print("Array_1: ", array_1)
print("Array_2: ", array_2)
print("Matching positions: ",positions)

Array_1:  [[6 6 9 7 0]]
Array_2:  [[8 9 8 7 7]]
Matching positions:  (array([0]), array([3]))


# **4.Create a 4X2 integer array and Prints its atributes such as shape,dimension and length.**


In [40]:
array = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])
print("Shape of the array: ",array.shape)
print("Dimension of the array: ",array.ndim)
print("Length of the array: ",len(array))

Shape of the array:  (4, 2)
Dimension of the array:  2
Length of the array:  4


# **5.Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.**

In [42]:
array = np.arange(100, 200, 10).reshape(5,2)
print("Required array: ", array)

Required array:  [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


# **6.Create a numpy array of 5*4 and return array of items by taking the third column from all rows**

In [50]:
array = np.random.randint(low=0, high=10, size=(5,4), dtype=int)
print("Original array: ", array)
req_array = array[:,2]
print("Required array: ",req_array)

Original array:  [[2 9 4 3]
 [9 1 3 4]
 [1 5 0 4]
 [1 3 7 1]
 [4 7 3 4]]
Required array:  [4 3 0 7 3]


# **7.Return array of odd rows and even columns from above numpy array**

In [52]:
req_array = array[1::2, 0::2]
print("req_array: ", req_array)

req_array:  [[9 3]
 [1 7]]


# **8.Delete the second column from a given array and insert the following new column in its place. sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) newColumn = numpy.array([[10,10,10]])**

In [63]:
given_array = np.array([[34,43,73],
                        [82,22,12],
                        [53,94,66]])
deleted_column_array = np.delete(given_array, 1, axis=1)
print("Deleted column array: ", deleted_column_array)
insert_array = np.array([[10,10,10]])
inserted_column_array = np.insert(deleted_column_array, 1, insert_array,axis=1)
print("Inserted column array: ",inserted_column_array)

Deleted column array:  [[34 73]
 [82 12]
 [53 66]]
Inserted column array:  [[34 10 73]
 [82 10 12]
 [53 10 66]]


# **9.Find the positions of: elements in x where its value is more than its corresponding element in y, and elements in x where its value is equals to its corresponding element in y**

In [73]:
x = np.random.randint(low=0, high=10, size=(1,5), dtype=int)
y = np.random.randint(low=0, high=10, size=(1,5), dtype=int)
more_than_positions = np.where(x > y)
equal_positions = np.where(x == y)
print(x,y)
print(more_than_positions)
print(equal_positions)

[[5 0 8 8 9]] [[6 0 4 3 6]]
(array([0, 0, 0]), array([2, 3, 4]))
(array([0]), array([1]))
